name = "MarchingCubes"
uuid = "299715c1-40a9-479a-aaf9-4a633d36f717"
version = "0.1"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
StaticArrays = "1"
julia = "1"

[targets]
test = ["BenchmarkTools", "Test"]
