name = "MarchingCubes"
uuid = "299715c1-40a9-479a-aaf9-4a633d36f717"
license = "MIT"
desc = "Efficient Implementation of Marching Cubes' Cases with Topological Guarantees"
authors = ["T Bltg <tf.bltg@gmail.com>"]
version = "0.1.11"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
PrecompileTools = "1"
StaticArrays = "0.12, 1"
julia = "1.10"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
PlyIO = "42171d58-473b-503a-8d5f-782019eb09ec"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BenchmarkTools", "GeometryBasics", "Meshes", "PlyIO", "Test"]
